name: Deploy Vinxi to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm ci
      - run: npm run build

      # Étape critique - Nettoyage et vérification
      - name: Prepare Deployment
        run: |
          # 1. Trouve le vrai dossier de build
          if [ -d "./.output/public" ]; then
            cp -R ./.output/public ./deploy
          elif [ -d "./dist" ]; then
            cp -R ./dist ./deploy
          else
            echo "::error::Aucun dossier de build trouvé!"
            exit 1
          fi

          # 2. Force le type MIME correct
          echo "<!DOCTYPE html>
          <html>
            <head>
              <meta charset='utf-8'>
              <title>Mon App</title>
            </head>
            <body>
              <div id='root'></div>
              <script src='/assets/index.js' type='module'></script>
            </body>
          </html>" > ./deploy/index.html

          # 3. Crée un fichier .nojekyll pour désinter le traitement Jekyll
          touch ./deploy/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy
        uses: actions/deploy-pages@v4