name: Deploy Vinxi to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - run: npm ci
      - run: npm run build

      - name: Debug build output
        run: |
          ls -R .output || true
          ls -R .out || true
          ls -R dist || true

      - name: Prepare Artifacts
        run: |
          mkdir -p ./deploy
          
          if [ -d "./.output/public" ]; then
            echo "Using .output/public structure"
            cp -R ./.output/public/* ./deploy/
          elif [ -d "./.out/public" ]; then
            echo "Using .out/public structure"
            cp -R ./.out/public/* ./deploy/
          elif [ -d "./dist" ]; then
            echo "Using dist structure"
            cp -R ./dist/* ./deploy/
          else
            echo "ERROR: No build output found!"
            exit 1
          fi
          
          # Crée 404.html seulement si index.html existe
          if [ -f "./deploy/index.html" ]; then
            cp ./deploy/index.html ./deploy/404.html
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy

      - name: Deploy
        uses: actions/deploy-pages@v4