name: Deploy Vinxi to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

      # Étape CRITIQUE - Trouve le vrai dossier
      - name: Locate Real Build Output
        id: find_output
        run: |
          if [ -f "./.output/public/index.html" ]; then
            echo "OUTPUT_DIR=.output/public" >> $GITHUB_OUTPUT
          elif [ -f "./.out/public/index.html" ]; then
            echo "OUTPUT_DIR=.out/public" >> $GITHUB_OUTPUT
          elif [ -f "./dist/index.html" ]; then
            echo "OUTPUT_DIR=dist" >> $GITHUB_OUTPUT
          else
            echo "::error::Aucun fichier index.html trouvé après le build!"
            exit 1
          fi

      # Déploie EXACTEMENT ce que Vinxi a généré
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.find_output.outputs.OUTPUT_DIR }}

      - name: Deploy
        uses: actions/deploy-pages@v4